### ISSUE TITLE
Weird error after updating to 4.2

### ISSUE THREAD

**Issue by Nanianmichaels** [simeononsecurity/docker-duino-coin#5]
Hello there.

It appears the most recent update to 4.2 might have broken my setup (it was working OK up to about 5 days ago, which was the last time I checked before going on vacation).

Copy of the relevant part of the log follows:

>Traceback (most recent call last):
  File "/app/duino-coin/PC_Miner.py", line 198, in title
    print('\33]0;' + title + '\a', end='')
  File "/usr/local/lib/python3.12/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.12/site-packages/colorama/ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python3.12/site-packages/colorama/ansitowin32.py", line 199, in write_and_convert
    text = self.convert_osc(text)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/colorama/ansitowin32.py", line 272, in convert_osc
    winterm.set_title(params[1])
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_title'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/duino-coin/PC_Miner.py", line 1390, in <module>
    title(f"{get_string('duco_python_miner')}{str(Settings.VER)})")
  File "/app/duino-coin/PC_Miner.py", line 201, in title
    debug_output("Error setting title: " +str(e))
    ^^^^^^^^^^^^
NameError: name 'debug_output' is not defined
>
Did I do anything wrong, or did a change on the main code just made the docker container explode?

Thanks in advance for any help.
